name: car_test
version: 0.0.1+1
description: a Flutter hotel_test App.
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.2"

dependencies:
  flutter:
    sdk: flutter

  # Color theme
  material_color_utilities: ^0.5.0

  # Localizations & Intl
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # Navigation
  auto_route: ^7.8.3

  # Widgets
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.3

# # Maps
#  yandex_mapkit: ^3.3.3

  # Firebase
  firebase_core: ^2.14.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.10.1

  # Animate
  rive: ^0.11.17

  # Bloc
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.3.6

  # Utils && Helpers
  shared_preferences: ^2.2.1
  mask_text_input_formatter: ^2.4.0
  google_fonts: ^6.0.0
  easy_mask: ^2.0.1

dev_dependencies:
  # Analyzer extensions
  dart_code_metrics_presets: ^2.4.0
  flutter_lints: ^2.0.3

  # Code generation
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0

#dependency_overrides:
flutter_gen:
  output: lib/src/core/resources
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo_animated.riv

#  fonts:
#    - family: SFProDisplay
#      fonts:
#        - asset: assets/fonts/SF-Pro-Display-Regular.otf
